#!/command/with-contenv bash
#shellcheck shell=bash

while ! pgrep pfclient &>/dev/null; do
    sleep 0.5
done
exec s6wrap --timestamps --quiet --prepend='pfclient_log' --args \
    tail -c 100k -F /var/log/pfclient/*.log
