#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC1091
source /scripts/common

if chk_enabled "${RADAR_STICK}"; then
    if [[ -z "${RADAR_STICK_DEVICE}" ]]; then
        RADAR_STICK_DEVICE=/dev/ttyUSB0 # default
    fi
    # can't run as nobody when trying to access serial device
    exec \
        s6wrap --ignore=stdout --quiet --prepend='pfclient_daemon' --args \
        /usr/local/bin/pfclient \
        --connection_type=2 \
        --address="${RADAR_STICK_DEVICE}" \
        --data_format=10 \
        --baudrate=3000000 \
        --sharecode="${SHARECODE}" \
        --lat="${LAT}" \
        --lon="${LONG}" \
        --pid_file=/run/pfclient.pid \
        --log_path=/var/log/pfclient
fi

exec s6-setuidgid nobody \
s6wrap --ignore=stdout --quiet --prepend='pfclient_daemon' --args \
/usr/local/bin/pfclient \
  --connection_type=1 \
  --address="${BEASTHOST}" \
  --port="${BEASTPORT}" \
  --data_format=1 \
  --sharecode="${SHARECODE}" \
  --lat="${LAT}" \
  --lon="${LONG}" \
  --pid_file=/run/pfclient.pid \
  --config_path=/config/pfclient-config.json \
  --log_path=/var/log/pfclient
