#!/command/with-contenv bash
#shellcheck shell=bash

# Test pfclient can run natively (without qemu)
if /usr/local/bin/pfclient --version > /dev/null 2>&1; then 
  # pfclient can be run natively
  s6-setuidgid nobody /usr/local/bin/pfclient \
    --connection_type=1 \
    --address="${BEASTHOST}" \
    --port="${BEASTPORT}" \
    --data_format=1 \
    --sharecode="${SHARECODE}" \
    --lat="${LAT}" \
    --lon="${LONG}" \
    --pid_file=/run/pfclient.pid \
    --config_path=/config/pfclient-config.json \
    --log_path=/var/log/pfclient \
    2>&1 | mawk -W Interactive '{print "[pfclient_daemon] " $0}'

else
  # pfclient needs qemu
  s6-setuidgid nobody qemu-arm-static /usr/local/bin/pfclient \
    --connection_type=1 \
    --address="${BEASTHOST}" \
    --port="${BEASTPORT}" \
    --data_format=1 \
    --sharecode="${SHARECODE}" \
    --lat="${LAT}" \
    --lon="${LONG}" \
    --pid_file=/run/pfclient.pid \
    --config_path=/config/pfclient-config.json \
    --log_path=/var/log/pfclient \
    2>&1 | mawk -W Interactive '{print "[pfclient_daemon] " $0}'
fi

